import { describe, expect, it } from 'vitest';
import { generateWorkerSecretCandidate } from './worker-secret';

describe('generateWorkerSecretCandidate', () => {
  it('encodes 32 cryptographically generated bytes as 64 lowercase hex characters', () => {
    const generated: ArrayBufferView[] = [];
    const randomSource: Pick<Crypto, 'getRandomValues'> = {
      getRandomValues<T extends ArrayBufferView>(array: T): T {
        generated.push(array);
        if (!(array instanceof Uint8Array)) throw new Error('Unexpected buffer');
        array.forEach((_, index) => {
          array[index] = index;
        });
        return array;
      },
    };

    const value = generateWorkerSecretCandidate(randomSource);

    expect(generated).toHaveLength(1);
    expect(generated[0]).toBeInstanceOf(Uint8Array);
    expect(generated[0]?.byteLength).toBe(32);
    expect(value).toBe(
      '000102030405060708090a0b0c0d0e0f'
      + '101112131415161718191a1b1c1d1e1f',
    );
    expect(value).toMatch(/^[\x21-\x7e]{32,256}$/u);
  });

  it('fails closed when a cryptographic random source is unavailable', () => {
    expect(() => generateWorkerSecretCandidate(null as never)).toThrow(
      'Web Crypto is unavailable.',
    );
  });
});
